name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    # Login to Docker Hub
    - name: Docker login
      run: docker login -u ${{ secrets.DockerHubUser }} -p ${{ secrets.DockerHubToken }}

    # Build and publish Docker image
    - name: Docker build and push
      run: docker build -f ${GITHUB_WORKSPACE}/Dockerfile -t ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:$(date +%d%m) . && docker push ${{ secrets.DockerHubUser }}/${IMAGE_NAME}:$(date +%d%m)
      env:
        IMAGE_NAME: github-workflow-example
